// Code generated by task operator:pin; DO NOT EDIT.

package operator

// PinnedModuleVersion is the operator module version (OperatorModulePath)
// 'opm operator install' installs when --version is not given. Refresh it
// only with 'task operator:pin VERSION=<version>'.
const PinnedModuleVersion = "0.1.0"

// PinnedOperatorVersion is the operator release PinnedModuleVersion deploys, as the
// module's operator package states it, "v"-prefixed.
const PinnedOperatorVersion = "v1.0.0-beta.8"
