name: Chore / Refactor
description: Cleanup, refactoring, or maintenance work
labels: ["chore"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be cleaned up or refactored?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the CLI does this affect?
      options:
        - mod apply
        - mod build
        - mod delete
        - mod diff
        - mod init
        - mod status
        - mod template
        - config
        - loader
        - kubernetes
        - output / UX
        - CUE integration
        - OCI / distribution
        - other
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this chore needed? What does it improve?
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: Files, packages, or areas affected. Estimated size of the change.
      placeholder: |
        - internal/build/executor.go (~190 lines to remove)
        - internal/build/executor_test.go (related tests)
    validations:
      required: false
