package cmdref

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	// BeginMarker opens the generated block of a page.
	BeginMarker = "<!-- generated by task docs:reference from the opm cobra commands; DO NOT EDIT -->"
	// EndMarker closes it.
	EndMarker = "<!-- end generated -->"
)

// Compose returns the file content for p. The generator owns the front matter
// and the block between the markers; when existing holds a page, the text
// between its front matter and the begin marker, and after the end marker, is
// kept as written.
func Compose(existing []byte, p Page) ([]byte, error) {
	before, after := "\n", ""
	if existing != nil {
		var err error
		before, after, err = authoredParts(string(existing))
		if err != nil {
			return nil, err
		}
	}
	var b strings.Builder
	b.WriteString(p.FrontMatter)
	b.WriteString(before)
	b.WriteString(BeginMarker + "\n\n")
	b.WriteString(p.Body)
	if !strings.HasSuffix(p.Body, "\n") {
		b.WriteString("\n")
	}
	b.WriteString("\n" + EndMarker + "\n")
	b.WriteString(after)
	return []byte(b.String()), nil
}

// authoredParts splits an existing page around its front matter and its
// generated block.
func authoredParts(s string) (before, after string, err error) {
	if !strings.HasPrefix(s, "---\n") {
		return "", "", errors.New("no front matter on line 1")
	}
	end := strings.Index(s[4:], "\n---\n")
	if end < 0 {
		return "", "", errors.New("front matter is not closed")
	}
	rest := s[4+end+len("\n---\n"):]
	begin := strings.Index(rest, BeginMarker+"\n")
	if begin < 0 || (begin > 0 && rest[begin-1] != '\n') {
		return "", "", errors.New("no generated block (begin marker missing)")
	}
	tail := rest[begin:]
	stop := strings.Index(tail, "\n"+EndMarker+"\n")
	if stop < 0 {
		return "", "", errors.New("generated block is not closed (end marker missing)")
	}
	return rest[:begin], tail[stop+len("\n"+EndMarker+"\n"):], nil
}

// Sync brings dir in line with pages. With check set it writes nothing and
// returns the files that differ: a page that is missing or stale, and a page
// carrying the generated marker that no command produces any more. Without
// check it writes every page that differs and removes those orphans. Files
// without the marker are authored and left alone.
func Sync(dir string, pages []Page, check bool) ([]string, error) {
	var stale []string
	want := map[string]bool{}
	for _, p := range pages {
		want[p.Name] = true
		path := filepath.Join(dir, p.Name)
		existing, err := os.ReadFile(path)
		if err != nil && !errors.Is(err, fs.ErrNotExist) {
			return nil, err
		}
		if errors.Is(err, fs.ErrNotExist) {
			existing = nil
		}
		content, err := Compose(existing, p)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		if bytes.Equal(existing, content) {
			continue
		}
		stale = append(stale, path)
		if check {
			continue
		}
		if err := os.MkdirAll(dir, 0o750); err != nil {
			return nil, err
		}
		if err := os.WriteFile(path, content, 0o644); err != nil { //nolint:gosec // a docs page, world-readable like the rest of the tree
			return nil, err
		}
	}

	orphans, err := orphanPages(dir, want)
	if err != nil {
		return nil, err
	}
	for _, path := range orphans {
		stale = append(stale, path)
		if !check {
			if err := os.Remove(path); err != nil {
				return nil, err
			}
		}
	}
	sort.Strings(stale)
	return stale, nil
}

// orphanPages lists the generated pages in dir that are not in want.
func orphanPages(dir string, want map[string]bool) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if errors.Is(err, fs.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var out []string
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") || want[e.Name()] {
			continue
		}
		path := filepath.Join(dir, e.Name())
		data, err := os.ReadFile(path)
		if err != nil {
			return nil, err
		}
		if bytes.Contains(data, []byte(BeginMarker)) {
			out = append(out, path)
		}
	}
	return out, nil
}
