// Package config provides configuration loading and management.
package config

import "fmt"

// DefaultRegistry is the default CUE_REGISTRY value used when initializing a
// fresh OPM configuration (the `config.registry` value in the generated
// config.cue).
const DefaultRegistry = "testing.opmodel.dev=ghcr.io/open-platform-model,opmodel.dev=ghcr.io/open-platform-model,registry.cue.works"

// DefaultConfigTemplate is the embedded template for ~/.opm/config.cue.
// Scalar data only — no CUE imports, no providers (enhancement 0006 D39).
var DefaultConfigTemplate = fmt.Sprintf(`// OPM CLI Configuration
// Generated by: opm config init
// Documentation: https://opmodel.dev/docs/cli/config
package config

config: {
	// registry is the default registry for CUE module resolution.
	// Override with --registry flag or OPM_REGISTRY env var.
	registry: %q

	kubernetes: {
		// kubeconfig is the path to the kubeconfig file.
		// Override with --kubeconfig flag or OPM_KUBECONFIG env var.
		kubeconfig: "~/.kube/config"

		// context is the Kubernetes context to use.
		// Override with --context flag or OPM_CONTEXT env var.
		// Default: current-context from kubeconfig
		context?: string

		// namespace is the default namespace for operations.
		// Override with --namespace flag or OPM_NAMESPACE env var.
		namespace: "default"
	}

	// log controls logging behavior.
	log: {
		// timestamps controls whether timestamps are shown in log output.
		// Override with --timestamps flag.
		timestamps: true

		// kubernetes controls Kubernetes-related log behavior.
		kubernetes: {
			// apiWarnings controls how K8s API deprecation warnings are displayed.
			// "warn"     - Show as WARN in log output
			// "debug"    - Only show with --verbose (default)
			// "suppress" - Drop entirely
			apiWarnings: "debug"
		}
	}
}
`, DefaultRegistry)

// DefaultCatalogPath is the major-suffixed CUE module path of the single
// first-party OPM catalog (enhancement 0010 D47). It is the catalog the
// generated default platform subscribes to and the one `opm operator install`
// resolves a published version of when it seeds the cluster Platform, so the
// path is spelled exactly once.
const DefaultCatalogPath = "opmodel.dev/catalogs/opm@v2"

// DefaultPlatformTemplate is the embedded template for ~/.opm/platform.cue —
// the local default platform (enhancement 0006 D39, D21 precedence source 3).
// Data-only projection of the Platform CR spec: wrapped in
// apiVersion/kind/metadata this document IS the cluster singleton Platform.
//
// The seeded catalog version pin is load-bearing and hand-bumped as catalog
// releases ship (`opm config init` is normatively offline — it cannot
// resolve "latest"). Its mirror peers, kept aligned in the same commit:
// hack/platform.cue (kind dev flow) and the operator's config/samples
// Platform. An immutable published tag never dangles, so the drift mode of
// a stale pin is "old but resolvable".
var DefaultPlatformTemplate = fmt.Sprintf(`// OPM local default platform
// Generated by: opm config init
// Used when no --platform flag is given and no cluster Platform CR is
// readable. Data only — CUE imports are not allowed in this file.
// Documentation: https://opmodel.dev/docs/cli/config

// name is the platform name. "cluster" matches the in-cluster singleton
// this file seeds on first apply against an empty cluster.
name: "cluster"

// type is an informational discriminator; it does not affect matching.
type: "kubernetes"

// registry subscribes this platform to catalogs by major-suffixed CUE
// module path. Each subscription pins exactly one published catalog build;
// bump the version by hand as catalog releases ship.
registry: {
	%q: {
		version: "2.0.0-alpha.3"
	}
}
`, DefaultCatalogPath)
