// Package config provides configuration loading and management.
package config

// DefaultConfigTemplate is the embedded template for config.cue.
const DefaultConfigTemplate = `// OPM CLI Configuration
// Generated by: opm config init
// Documentation: https://opmodel.dev/docs/cli/config
package config

import (
	provs "opmodel.dev/providers@v0"
)

config: {
	// registry is the default registry for CUE module resolution.
	// Override with --registry flag or OPM_REGISTRY env var.
	registry: "opmodel.dev=localhost:5000+insecure,registry.cue.works"

	// providers maps provider aliases to their definitions.
	// Providers are loaded from the registry via CUE imports.
	providers: {
		kubernetes: provs.#Registry["kubernetes"]
	}

	kubernetes: {
		// kubeconfig is the path to the kubeconfig file.
		// Override with --kubeconfig flag or OPM_KUBECONFIG env var.
		kubeconfig: "~/.kube/config"

		// context is the Kubernetes context to use.
		// Override with --context flag or OPM_CONTEXT env var.
		// Default: current-context from kubeconfig
		context?: string

		// namespace is the default namespace for operations.
		// Override with --namespace flag or OPM_NAMESPACE env var.
		namespace: "default"
	}

	// log controls logging behavior.
	log?: {
		// timestamps controls whether timestamps are shown in log output.
		// Override with --timestamps flag.
		timestamps: bool | *true

		// kubernetes controls Kubernetes-related log behavior.
		kubernetes: {
			// apiWarnings controls how K8s API deprecation warnings are displayed.
			// "warn"     - Show as WARN in log output (default)
			// "debug"    - Only show with --verbose
			// "suppress" - Drop entirely
			apiWarnings: "warn" | "debug" | "suppress" | *"warn"
		}
	}
}
`

// DefaultModuleTemplate is the embedded template for cue.mod/module.cue.
// Deps
const DefaultModuleTemplate = `module: "opmodel.dev/config@v0"

language: {
	version: "v0.15.0"
}
`
